In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('mumbai_flats_cleaned_v6.csv')
df

flat_type  flat_price        location1  buildupArea_sqft  \
0     3 BHK Flat        3.95  Kanjurmarg West              1550   
1     1 BHK Flat        0.19          Palghar               630   
2     1 BHK Flat        0.73   Mira Road East               580   
3     1 BHK Flat        1.10     Dahisar East               410   
4     3 BHK Flat        2.25           others              1052   
...          ...         ...              ...               ...   
7478  2 BHK Flat        2.25          Chembur               960   
7479  3 BHK Flat        2.85          Chembur               865   
7480  3 BHK Flat        2.60      Mulund West               886   
7481  2 BHK Flat        0.65   Mira Road East               625   
7482  1 BHK Flat        0.20     Naigaon East               280   

      avg_price_thousands      age_of_property floor_type       furnishing  \
0                 25480.0  recent construction     Higher  Fully Furnished   
1                  3020.0  recent construction     Middle      Unfurnished   
2                 12590.0     new construction      Lower   Semi Furnished   
3                 26830.0     new construction     Higher   Semi Furnished   
4                 21390.0     new construction      Lower   Semi Furnished   
...                   ...                  ...        ...              ...   
7478              23440.0  recent construction     Higher   Semi Furnished   
7479              32950.0  recent construction     Higher   Semi Furnished   
7480              29340.0      modern property     Higher  Fully Furnished   
7481              10400.0      modern property      Lower   Semi Furnished   
7482               7140.0  recent construction      Lower   Semi Furnished   

      bedrooms  bathrooms  balcony parking  
0            3          2        1     yes  
1            1          1        2     yes  
2            1          2        2      no  
3            1          2        1     yes  
4            3          2        3     yes  
...        ...        ...      ...     ...  
7478         2          2        0     yes  
7479         3          3        0     yes  
7480         3          3        0     yes  
7481         2          2        0      no  
7482         1          1        0      no  

[7483 rows x 12 columns]

In [3]:
df.isna().sum()

flat_type               0
flat_price              0
location1               0
buildupArea_sqft        0
avg_price_thousands     0
age_of_property         0
floor_type             35
furnishing              0
bedrooms                0
bathrooms               0
balcony                 0
parking                 0
dtype: int64

In [4]:
df.drop(columns=['avg_price_thousands','floor_type'],inplace=True)

In [5]:
df[['flat_price','buildupArea_sqft','bedrooms','bathrooms','balcony']].corr()

flat_price  buildupArea_sqft  bedrooms  bathrooms   balcony
flat_price          1.000000          0.830644  0.736896   0.558146 -0.028075
buildupArea_sqft    0.830644          1.000000  0.834519   0.652503  0.142133
bedrooms            0.736896          0.834519  1.000000   0.702497  0.054421
bathrooms           0.558146          0.652503  0.702497   1.000000  0.098754
balcony            -0.028075          0.142133  0.054421   0.098754  1.000000

In [9]:
df['age_of_property'].unique()

array(['recent construction', 'new construction', 'modern property',
       'mid age property', 'old propert'], dtype=object)

In [18]:
from scipy.stats import f_oneway
recent = df[df['age_of_property'] == 'recent construction']['flat_price']
new  = df[df['age_of_property'] == 'new construction']['flat_price']
modern = df[df['age_of_property'] == 'modern property']['flat_price']
mid = df[df['age_of_property'] == 'mid age property']['flat_price']
old = df[df['age_of_property'] == 'old propert']['flat_price']
f_oneway(recent,new,modern,mid,old)

F_onewayResult(statistic=7.900296152457569, pvalue=2.376119151540775e-06)

### since p-value is less tha 0.05 we reject the null hypothesis and conclude that the age of the property have different mean 

In [20]:
df.head()

flat_type  flat_price        location1  buildupArea_sqft  \
0  3 BHK Flat        3.95  Kanjurmarg West              1550   
1  1 BHK Flat        0.19          Palghar               630   
2  1 BHK Flat        0.73   Mira Road East               580   
3  1 BHK Flat        1.10     Dahisar East               410   
4  3 BHK Flat        2.25           others              1052   

       age_of_property       furnishing  bedrooms  bathrooms  balcony parking  
0  recent construction  Fully Furnished         3          2        1     yes  
1  recent construction      Unfurnished         1          1        2     yes  
2     new construction   Semi Furnished         1          2        2      no  
3     new construction   Semi Furnished         1          2        1     yes  
4     new construction   Semi Furnished         3          2        3     yes

In [21]:
df['furnishing'].unique()

array(['Fully Furnished', 'Unfurnished', 'Semi Furnished'], dtype=object)

In [22]:
full = df[df['furnishing'] == 'Fully Furnished']['flat_price']
unfur = df[df['furnishing'] == 'Unfurnished']['flat_price']
semi= df[df['furnishing'] == 'Semi Furnished']['flat_price']
f_oneway(full,unfur,semi)

F_onewayResult(statistic=70.04330847191093, pvalue=7.24622113855542e-31)

In [32]:
df.head()

flat_type  flat_price        location1  buildupArea_sqft  \
0  3 BHK Flat        3.95  Kanjurmarg West              1550   
1  1 BHK Flat        0.19          Palghar               630   
2  1 BHK Flat        0.73   Mira Road East               580   
3  1 BHK Flat        1.10     Dahisar East               410   
4  3 BHK Flat        2.25           others              1052   

       age_of_property       furnishing  bedrooms  bathrooms  balcony parking  
0  recent construction  Fully Furnished         3          2        1     yes  
1  recent construction      Unfurnished         1          1        2     yes  
2     new construction   Semi Furnished         1          2        2      no  
3     new construction   Semi Furnished         1          2        1     yes  
4     new construction   Semi Furnished         3          2        3     yes

In [33]:
df['bedrooms'].unique()

array([3, 1, 2, 4, 6, 5], dtype=int64)

In [34]:
one = df[df['bedrooms'] == 1]['flat_price']
two = df[df['bedrooms'] ==  2]['flat_price']
three= df[df['bedrooms'] == 3]['flat_price']
four= df[df['bedrooms'] == 4]['flat_price']
five= df[df['bedrooms'] == 5]['flat_price']
six= df[df['bedrooms'] == 6]['flat_price']
f_oneway(one,two,three,four,five,six)

F_onewayResult(statistic=2007.8489593618704, pvalue=0.0)

In [35]:
df['bathrooms'].unique()

array([2, 1, 3, 4, 5, 6], dtype=int64)

In [36]:
one = df[df['bathrooms'] == 1]['flat_price']
two = df[df['bathrooms'] ==  2]['flat_price']
three= df[df['bathrooms'] == 3]['flat_price']
four= df[df['bathrooms'] == 4]['flat_price']
five= df[df['bathrooms'] == 5]['flat_price']
six= df[df['bathrooms'] == 6]['flat_price']
f_oneway(one,two,three,four,five,six)

F_onewayResult(statistic=826.9416807602239, pvalue=0.0)

In [37]:
df['balcony'].unique()

array([1, 2, 3, 0, 4, 5], dtype=int64)

In [39]:
one = df[df['balcony'] == 1]['flat_price']
two = df[df['balcony'] ==  2]['flat_price']
three= df[df['balcony'] == 3]['flat_price']
four= df[df['balcony'] == 4]['flat_price']
five= df[df['balcony'] == 5]['flat_price']
zero= df[df['balcony'] == 0]['flat_price']
f_oneway(one,two,three,four,five,zero)

F_onewayResult(statistic=45.3445088943865, pvalue=2.7510618003815253e-46)

In [40]:
df

flat_type  flat_price        location1  buildupArea_sqft  \
0     3 BHK Flat        3.95  Kanjurmarg West              1550   
1     1 BHK Flat        0.19          Palghar               630   
2     1 BHK Flat        0.73   Mira Road East               580   
3     1 BHK Flat        1.10     Dahisar East               410   
4     3 BHK Flat        2.25           others              1052   
...          ...         ...              ...               ...   
7527  2 BHK Flat        2.25          Chembur               960   
7528  3 BHK Flat        2.85          Chembur               865   
7529  3 BHK Flat        2.60      Mulund West               886   
7530  2 BHK Flat        0.65   Mira Road East               625   
7531  1 BHK Flat        0.20     Naigaon East               280   

          age_of_property       furnishing  bedrooms  bathrooms  balcony  \
0     recent construction  Fully Furnished         3          2        1   
1     recent construction      Unfurnished         1          1        2   
2        new construction   Semi Furnished         1          2        2   
3        new construction   Semi Furnished         1          2        1   
4        new construction   Semi Furnished         3          2        3   
...                   ...              ...       ...        ...      ...   
7527  recent construction   Semi Furnished         2          2        0   
7528  recent construction   Semi Furnished         3          3        0   
7529      modern property  Fully Furnished         3          3        0   
7530      modern property   Semi Furnished         2          2        0   
7531  recent construction   Semi Furnished         1          1        0   

     parking  
0        yes  
1        yes  
2         no  
3        yes  
4        yes  
...      ...  
7527     yes  
7528     yes  
7529     yes  
7530      no  
7531      no  

[7532 rows x 10 columns]

In [6]:
new_df = df.copy()

In [7]:
new_df

flat_type  flat_price        location1  buildupArea_sqft  \
0     3 BHK Flat        3.95  Kanjurmarg West              1550   
1     1 BHK Flat        0.19          Palghar               630   
2     1 BHK Flat        0.73   Mira Road East               580   
3     1 BHK Flat        1.10     Dahisar East               410   
4     3 BHK Flat        2.25           others              1052   
...          ...         ...              ...               ...   
7478  2 BHK Flat        2.25          Chembur               960   
7479  3 BHK Flat        2.85          Chembur               865   
7480  3 BHK Flat        2.60      Mulund West               886   
7481  2 BHK Flat        0.65   Mira Road East               625   
7482  1 BHK Flat        0.20     Naigaon East               280   

          age_of_property       furnishing  bedrooms  bathrooms  balcony  \
0     recent construction  Fully Furnished         3          2        1   
1     recent construction      Unfurnished         1          1        2   
2        new construction   Semi Furnished         1          2        2   
3        new construction   Semi Furnished         1          2        1   
4        new construction   Semi Furnished         3          2        3   
...                   ...              ...       ...        ...      ...   
7478  recent construction   Semi Furnished         2          2        0   
7479  recent construction   Semi Furnished         3          3        0   
7480      modern property  Fully Furnished         3          3        0   
7481      modern property   Semi Furnished         2          2        0   
7482  recent construction   Semi Furnished         1          1        0   

     parking  
0        yes  
1        yes  
2         no  
3        yes  
4        yes  
...      ...  
7478     yes  
7479     yes  
7480     yes  
7481      no  
7482      no  

[7483 rows x 10 columns]

In [8]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()
new_df['flat_type'] = encoder.fit_transform(new_df['flat_type'].values.reshape(-1,1))
new_df['location1'] = encoder.fit_transform(new_df['location1'].values.reshape(-1,1))
new_df['age_of_property'] = encoder.fit_transform(new_df['age_of_property'].values.reshape(-1,1))
new_df['furnishing'] = encoder.fit_transform(new_df['furnishing'].values.reshape(-1,1))
new_df['parking'] = encoder.fit_transform(new_df['parking'].values.reshape(-1,1))

In [9]:
new_df.corr()['flat_price']

flat_type           0.738854
flat_price          1.000000
location1          -0.043592
buildupArea_sqft    0.830644
age_of_property     0.002232
furnishing         -0.140588
bedrooms            0.736896
bathrooms           0.558146
balcony            -0.028075
parking             0.168737
Name: flat_price, dtype: float64

In [10]:
X = new_df.drop(columns=['flat_price'],axis=1)
y = df['flat_price']

In [50]:
y

0       3.95
1       0.19
2       0.73
3       1.10
4       2.25
        ... 
7527    2.25
7528    2.85
7529    2.60
7530    0.65
7531    0.20
Name: flat_price, Length: 7532, dtype: float64

In [11]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=100,random_state=42)
rf.fit(X,y)

rf_data = pd.DataFrame({'features':X.columns,
                        'rf_imp':rf.feature_importances_})

In [12]:
rf_data.sort_values(by='rf_imp',ascending=False)

features    rf_imp
2  buildupArea_sqft  0.721376
1         location1  0.130562
5          bedrooms  0.035322
7           balcony  0.030688
0         flat_type  0.024218
3   age_of_property  0.023188
6         bathrooms  0.017074
4        furnishing  0.015605
8           parking  0.001967

In [13]:
from sklearn.ensemble import GradientBoostingRegressor

gr = GradientBoostingRegressor()
gr.fit(X,y)

gr_data = pd.DataFrame({'features':X.columns,
                        'gr_imp':gr.feature_importances_})

gr_data.sort_values(by='gr_imp',ascending=False)

features    gr_imp
2  buildupArea_sqft  0.791599
1         location1  0.112907
0         flat_type  0.037257
5          bedrooms  0.028403
7           balcony  0.019111
3   age_of_property  0.005848
6         bathrooms  0.003052
4        furnishing  0.001450
8           parking  0.000374

In [14]:
df.shape

(7483, 10)

In [15]:
df.sample(7483).to_csv('data_for_model.csv',index=False)